"""
config.py  (root level) — BACKWARDS COMPATIBILITY SHIM
All constants now live in pipeline/core/config.py.
This file re-exports everything so existing imports continue working.
Do NOT add new constants here — use pipeline/core/config.py.
"""
from pipeline.core.config import *
from pipeline.core.config import (
    BASE_DIR, OUTPUT_DIR, CHUNKS_DIR, TRANSCRIPTS_DIR, ANALYSIS_DIR,
    DECISIONS_DIR, REPORTS_DIR, DATABASE_PATH, DATABASE_URL,
    SAMPLE_RATE, CHUNK_WINDOW_SEC, CHUNK_OVERLAP_SEC, VAD_AGGRESSIVENESS,
    WHISPER_MODEL_SIZE, WHISPER_DEVICE, WHISPER_BEAM_SIZE, WORD_CONFIDENCE_MIN,
    EMOTION_MODEL, EMERGENCY_MODEL, EMERGENCY_LABELS, EMERGENCY_LABEL_SHORT,
    EMERGENCY_THRESHOLD, MIN_WORDS_FOR_EMERGENCY,
    WEIGHT_EMOTION, WEIGHT_EMERGENCY, WEIGHT_KEYWORD,
    ZONE_YELLOW, ZONE_RED,
    TWILIO_ENABLED, EMAIL_ENABLED, validate_config,
)

# Legacy aliases used by existing test scripts
INPUT_AUDIO_DIR    = str(BASE_DIR / "input" / "audio")
DATASET_DIR        = str(BASE_DIR / "input" / "datasets")
OUTPUT_CHUNKS_DIR  = str(CHUNKS_DIR)
OUTPUT_TRANSCRIPTS = str(TRANSCRIPTS_DIR)
OUTPUT_ANALYSIS    = str(ANALYSIS_DIR)
OUTPUT_DECISIONS   = str(DECISIONS_DIR)
OUTPUT_REPORTS     = str(REPORTS_DIR)
DATABASE_PATH_STR  = str(DATABASE_PATH)

CONFIDENCE_THRESHOLD  = WORD_CONFIDENCE_MIN
ZONE_GREEN_MAX        = ZONE_YELLOW    # old name
ZONE_YELLOW_MAX       = ZONE_RED       # old name
ESCALATION_COUNT      = 3
NOISE_REDUCE_STRENGTH = 0.75